const STORAGE = { items: "calendar.items.v1", reminders: "calendar.reminders.v1" };
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const fmtDate = date => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const parseDate = value => { const [y,m,d] = value.split("-").map(Number); return new Date(y,m-1,d); };
const addDays = (date, amount) => { const copy = new Date(date); copy.setDate(copy.getDate()+amount); return copy; };
const escapeHTML = value => String(value ?? "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));

const CATEGORIES = {health:"Health",academic:"Academic",personal:"Personal",finance:"Finance",dating:"Dating",family:"Friends & Family"};
const TYPES = {appointment:"Appointment",communication:"Communication",task:"Task",reminder:"Reminder",event:"Event"};
const demoItems = [
  {id:crypto.randomUUID(),title:"Dentist appointment",category:"health",type:"appointment",date:fmtDate(new Date()),start:"14:00",end:"16:00",location:"Center City",notes:[{id:crypto.randomUUID(),text:"Bring insurance card",createdAt:new Date().toISOString()}],important:true,repeat:"none",reminder:"60",completed:false},
  {id:crypto.randomUUID(),title:"Anatomy study block",category:"academic",type:"task",date:fmtDate(addDays(new Date(),1)),start:"08:00",end:"10:00",location:"",notes:[{id:crypto.randomUUID(),text:"Review the cardiovascular system",createdAt:new Date().toISOString()}],important:false,repeat:"none",reminder:"30",completed:false},
  {id:crypto.randomUUID(),title:"Grocery shopping",category:"personal",type:"task",date:fmtDate(addDays(new Date(),2)),start:"19:00",end:"",location:"",notes:[],important:false,repeat:"none",reminder:"none",completed:false}
];

const state = {
  page:"dashboard", view:"week", cursor:new Date(), selectedDate:fmtDate(new Date()), selectedRows:new Set(), expandedRows:new Set(), drawerItemId:null, undoItems:[],
  items:JSON.parse(localStorage.getItem(STORAGE.items) || "null") || demoItems,
  reminders:JSON.parse(localStorage.getItem(STORAGE.reminders) || "{}"),
  supabase:null, user:null
};

function saveLocal(){localStorage.setItem(STORAGE.items,JSON.stringify(state.items));localStorage.setItem(STORAGE.reminders,JSON.stringify(state.reminders));}
function mondayOf(date){const copy=new Date(date);const day=copy.getDay()||7;copy.setDate(copy.getDate()-day+1);copy.setHours(0,0,0,0);return copy;}
function readableTime(value){if(!value)return "All day";const [h,m]=value.split(":").map(Number);return new Intl.DateTimeFormat([], {hour:"numeric",minute:"2-digit"}).format(new Date(2000,0,1,h,m));}
function longDate(value){return parseDate(value).toLocaleDateString([], {weekday:"long",month:"long",day:"numeric"});}
function recurrenceMatches(item,dateString){
  if(item.date===dateString)return true;if(!item.repeat||item.repeat==="none"||dateString<item.date)return false;
  const start=parseDate(item.date),date=parseDate(dateString),days=Math.round((date-start)/86400000);
  if(item.repeat==="daily")return true;if(item.repeat==="weekly")return days%7===0;
  if(item.repeat==="weekdays")return date.getDay()>0&&date.getDay()<6;
  if(item.repeat==="monthly")return date.getDate()===start.getDate();return false;
}
function normalizeItem(item){const status=item.status||(item.completed?"completed":"planned");return {...item,category:item.category||(item.type==="academic"?"academic":"personal"),type:TYPES[item.type]?item.type:"event",notes:Array.isArray(item.notes)?item.notes:(item.notes?[{id:crypto.randomUUID(),text:item.notes,createdAt:new Date().toISOString()}]:[]),important:Boolean(item.important),status,completed:status==="completed"};}
state.items=state.items.map(normalizeItem);
function itemsForDate(dateString){return state.items.filter(item=>recurrenceMatches(item,dateString)).sort((a,b)=>Number(b.important)-Number(a.important)||(a.start||"99:99").localeCompare(b.start||"99:99"));}

function render(){
  renderDashboard();
  renderItemsTable();
  const board=$("#calendarBoard");board.className=`board ${state.view}`;board.innerHTML="";
  let dates=[];
  if(state.view==="week"){const start=mondayOf(state.cursor);dates=Array.from({length:7},(_,i)=>addDays(start,i));$("#periodTitle").textContent=`${start.toLocaleDateString([], {month:"long",day:"numeric"})} – ${addDays(start,6).toLocaleDateString([], {month:"long",day:"numeric",year:"numeric"})}`;}
  else{const first=new Date(state.cursor.getFullYear(),state.cursor.getMonth(),1);const start=mondayOf(first);dates=Array.from({length:42},(_,i)=>addDays(start,i));$("#periodTitle").textContent=state.cursor.toLocaleDateString([], {month:"long",year:"numeric"});}
  for(const date of dates)board.append(dayCell(date));
  $$(".view-switcher button").forEach(button=>button.classList.toggle("active",button.dataset.view===state.view));renderUpNext();
}
function dayCell(date){
  const dateString=fmtDate(date),items=itemsForDate(dateString),cell=document.createElement("article");
  cell.className="day-column";if(dateString===fmtDate(new Date()))cell.classList.add("today");if(state.view==="month"&&date.getMonth()!==state.cursor.getMonth())cell.classList.add("outside");cell.dataset.date=dateString;
  cell.innerHTML=`<header class="day-header"><span class="day-name">${date.toLocaleDateString([], {weekday:"short"}).toUpperCase()}</span><span class="day-number">${date.getDate()}</span></header><div class="pins"></div><button class="add-day" type="button" aria-label="Add item">＋</button>`;
  const pins=cell.querySelector(".pins"),limit=state.view==="month"?3:8;
  items.slice(0,limit).forEach(item=>pins.append(pin(item,dateString)));if(items.length>limit)pins.insertAdjacentHTML("beforeend",`<div class="more-pins">+${items.length-limit} more</div>`);
  cell.addEventListener("click",event=>{if(!event.target.closest(".pin")&&!event.target.closest(".add-day"))openDay(dateString)});
  cell.querySelector(".add-day").addEventListener("click",event=>{event.stopPropagation();openItemForm(null,dateString)});
  cell.addEventListener("dragover",event=>event.preventDefault());cell.addEventListener("drop",event=>{event.preventDefault();const id=event.dataTransfer.getData("text/plain"),item=state.items.find(x=>x.id===id);if(item){item.date=dateString;saveAndSync();render();toast("Item moved");}});return cell;
}
function pin(item,occurrenceDate){
  const button=document.createElement("button");button.type="button";button.className=`pin ${item.category}${item.completed?" completed":""}${item.important?" important":""}`;button.draggable=true;button.innerHTML=`<strong>${item.important?'<span class="pin-star">★</span>':""}${escapeHTML(item.title)}</strong><small>${TYPES[item.type]} · ${item.start?readableTime(item.start):"All day"}${item.location?` · ${escapeHTML(item.location)}`:""}</small>`;
  button.addEventListener("dragstart",event=>event.dataTransfer.setData("text/plain",item.id));button.addEventListener("click",event=>{event.stopPropagation();openDay(occurrenceDate);openDrawerDetail(item.id)});return button;
}
function renderUpNext(){
  const list=$("#upNextList"),today=fmtDate(new Date());const upcoming=state.items.filter(item=>!item.completed&&item.date>=today).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)).slice(0,3);
  list.innerHTML=upcoming.length?upcoming.map(item=>`<article class="up-card"><span class="up-dot" style="background:var(--${item.category})"></span><div><strong>${item.important?"★ ":""}${escapeHTML(item.title)}</strong><small>${longDate(item.date)} · ${readableTime(item.start)}</small></div></article>`).join(""):`<div class="empty-state">Nothing upcoming. Enjoy the open space.</div>`;
}

function dashboardPin(item){return `<button class="dash-pin" type="button" data-dash-item="${item.id}"><span class="category-dot" style="background:var(--${item.category})"></span><span><strong>${item.important?'<span class="star">★</span> ':""}${escapeHTML(item.title)}</strong><small>${CATEGORIES[item.category]} · ${TYPES[item.type]} · ${longDate(item.date)}${item.start?` at ${readableTime(item.start)}`:""}</small></span></button>`;}
function renderDashboard(){
  $("#dashboardDate").textContent=new Date().toLocaleDateString([], {weekday:"long",month:"long",day:"numeric",year:"numeric"});const today=fmtDate(new Date());
  const todayItems=itemsForDate(today),important=state.items.filter(x=>x.important&&!x.completed).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5),upcoming=state.items.filter(x=>x.date>today&&!x.completed).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5),tasks=state.items.filter(x=>x.type==="task"&&!x.completed).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5);
  const fill=(selector,items,message)=>$(selector).innerHTML=items.length?items.map(dashboardPin).join(""):`<div class="empty-state">${message}</div>`;fill("#todayPins",todayItems,"Nothing pinned for today.");fill("#importantPins",important,"No important items.");fill("#upcomingPins",upcoming,"Nothing upcoming.");fill("#taskPins",tasks,"No open tasks.");
  $("#categorySummary").innerHTML=Object.entries(CATEGORIES).map(([key,label])=>`<div class="category-chip" style="background:var(--${key})"><strong>${state.items.filter(x=>x.category===key&&!x.completed).length}</strong>${label}</div>`).join("");
  $$('[data-dash-item]').forEach(button=>button.addEventListener("click",()=>{const item=state.items.find(x=>x.id===button.dataset.dashItem);openDay(item.date);openDrawerDetail(item.id);}));
}
function openDay(dateString){
  state.selectedDate=dateString;showDrawerView("day");$("#drawerTitle").textContent=longDate(dateString);$("#dailyReminder").value=state.reminders[dateString]||"";renderDrawerItems();$("#scrim").hidden=false;$("#dayDrawer").classList.add("open");$("#dayDrawer").setAttribute("aria-hidden","false");
}
function closeDay(){$("#dayDrawer").classList.remove("open");$("#dayDrawer").setAttribute("aria-hidden","true");$("#scrim").hidden=true;}
function showDrawerView(view){$("#drawerDayView").hidden=view!=="day";$("#drawerDetailView").hidden=view!=="detail";$("#drawerFormView").hidden=view!=="form";$("#drawerEyebrow").textContent=view==="day"?"SELECTED DAY":view==="detail"?"ITEM DETAILS":"INLINE EDITOR";if(view==="day")$("#drawerTitle").textContent=longDate(state.selectedDate);}
function renderDrawerItems(){
  const list=$("#drawerItems"),items=itemsForDate(state.selectedDate);list.innerHTML=items.length?items.map(item=>`<article class="drawer-item ${item.category} ${item.status}"><header><button type="button" data-edit="${item.id}"><strong>${item.important?"★ ":""}${escapeHTML(item.title)}</strong><small>${CATEGORIES[item.category]} · ${TYPES[item.type]} · ${item.status}</small></button><small>${readableTime(item.start)}</small></header>${item.location?`<p>⌖ ${escapeHTML(item.location)}</p>`:""}${item.notes.map(note=>`<p class="drawer-note">${escapeHTML(note.text)}</p>`).join("")}${item.type==="task"?`<label class="task-check"><input type="checkbox" data-complete="${item.id}" ${item.completed?"checked":""}> ${item.completed?"Completed":"Mark complete"}</label>`:""}</article>`).join(""):`<div class="empty-state">No pins for this day yet.</div>`;
  $$('[data-edit]').forEach(button=>button.addEventListener("click",()=>openDrawerDetail(button.dataset.edit)));
  $$('[data-complete]').forEach(box=>box.addEventListener("change",()=>{const item=state.items.find(x=>x.id===box.dataset.complete);item.completed=box.checked;item.status=box.checked?"completed":"planned";saveAndSync();renderDrawerItems();render();}));
}
function openDrawerDetail(id){const item=state.items.find(x=>x.id===id);if(!item)return;state.drawerItemId=id;$("#drawerTitle").textContent=item.title;$("#drawerDetail").innerHTML=`<div class="detail-badges"><span style="background:var(--${item.category})">${CATEGORIES[item.category]}</span><span>${TYPES[item.type]}</span>${item.important?"<span>★ Important</span>":""}</div><dl class="item-details"><div><dt>Date</dt><dd>${longDate(item.date)}</dd></div><div><dt>Time</dt><dd>${item.start?`${readableTime(item.start)}${item.end?`–${readableTime(item.end)}`:""}`:"All day"}</dd></div><div><dt>Status</dt><dd>${item.status}</dd></div>${item.location?`<div><dt>Location / Link</dt><dd>${/^https?:\/\//.test(item.location)?`<a href="${escapeHTML(item.location)}" target="_blank" rel="noopener">${escapeHTML(item.location)}</a>`:escapeHTML(item.location)}</dd></div>`:""}<div><dt>Repeats</dt><dd>${item.repeat}</dd></div><div><dt>Notification</dt><dd>${item.reminder==="none"?"None":`${item.reminder} minutes before`}</dd></div></dl><section class="detail-notes"><h3>Notes</h3>${item.notes.length?item.notes.map(n=>`<article><p>${escapeHTML(n.text)}</p><small>${new Date(n.createdAt).toLocaleString()}</small></article>`).join(""):'<p class="muted">No notes yet.</p>'}</section>`;showDrawerView("detail");}
function drawerFormHTML(item){const value=(x)=>escapeHTML(x||"");return `<input type="hidden" name="id" value="${item?.id||""}"><div class="field"><label>Title</label><input name="title" required value="${value(item?.title)}"></div><div class="form-row"><div class="field"><label>Category</label><select name="category">${optionTags(CATEGORIES,item?.category||"personal")}</select></div><div class="field"><label>Type</label><select name="type">${optionTags(TYPES,item?.type||"event")}</select></div></div><div class="field"><label>Date</label><input name="date" type="date" required value="${item?.date||state.selectedDate}"></div><div class="form-row"><div class="field"><label>Start</label><input name="start" type="time" value="${item?.start||""}"></div><div class="field"><label>End</label><input name="end" type="time" value="${item?.end||""}"></div></div><div class="field"><label>Location / Link</label><input name="location" value="${value(item?.location)}"></div><div class="form-row"><div class="field"><label>Status</label><select name="status">${optionTags({planned:"Planned",progress:"In progress",completed:"Completed",cancelled:"Cancelled"},item?.status||"planned")}</select></div><div class="field"><label>Repeat</label><select name="repeat">${optionTags({none:"Doesn't repeat",daily:"Daily",weekly:"Weekly",monthly:"Monthly",weekdays:"Weekdays"},item?.repeat||"none")}</select></div></div><div class="field"><label>Notify</label><select name="reminder">${optionTags({none:"No notification",0:"At start",10:"10 minutes before",30:"30 minutes before",60:"1 hour before",1440:"1 day before"},item?.reminder||"none")}</select></div><label class="important-check"><input name="important" type="checkbox" ${item?.important?"checked":""}><span>★</span> Mark as important</label><div class="drawer-note-editor"><label>Notes</label><div data-drawer-notes>${(item?.notes||[]).map(n=>`<div class="drawer-note-input" data-note-id="${n.id}"><textarea rows="2">${escapeHTML(n.text)}</textarea><button type="button" data-remove-drawer-note>×</button></div>`).join("")}</div><button class="text-button" data-add-drawer-note type="button">＋ Add note</button></div><div class="drawer-form-actions"><button class="secondary-button" data-cancel-drawer type="button">Cancel</button><button class="primary-button" type="submit">Save item</button></div>`;}
function openDrawerForm(item=null){state.drawerItemId=item?.id||null;$("#drawerTitle").textContent=item?"Edit item":"Add to this day";const form=$("#drawerItemForm");form.innerHTML=drawerFormHTML(item);showDrawerView("form");bindDrawerForm();}
function bindDrawerForm(){const form=$("#drawerItemForm");form.querySelector('[data-cancel-drawer]').addEventListener("click",()=>state.drawerItemId?openDrawerDetail(state.drawerItemId):showDrawerView("day"));form.querySelector('[data-add-drawer-note]').addEventListener("click",()=>{const wrap=form.querySelector('[data-drawer-notes]'),row=document.createElement("div");row.className="drawer-note-input";row.dataset.noteId=crypto.randomUUID();row.innerHTML='<textarea rows="2" placeholder="Write a note…"></textarea><button type="button" data-remove-drawer-note>×</button>';wrap.append(row);row.querySelector("button").addEventListener("click",()=>row.remove());});form.querySelectorAll('[data-remove-drawer-note]').forEach(b=>b.addEventListener("click",()=>b.closest('.drawer-note-input').remove()));form.addEventListener("submit",event=>{event.preventDefault();const data=new FormData(form),existing=state.items.find(x=>x.id===data.get("id")),status=data.get("status"),item=normalizeItem({...(existing||{}),id:existing?.id||crypto.randomUUID(),title:data.get("title").trim(),category:data.get("category"),type:data.get("type"),date:data.get("date"),start:data.get("start"),end:data.get("end"),location:data.get("location").trim(),status,important:data.get("important")==="on",repeat:data.get("repeat"),reminder:data.get("reminder"),notes:[...form.querySelectorAll('.drawer-note-input')].map(row=>({id:row.dataset.noteId||crypto.randomUUID(),text:row.querySelector('textarea').value.trim(),createdAt:existing?.notes.find(n=>n.id===row.dataset.noteId)?.createdAt||new Date().toISOString()})).filter(n=>n.text)});if(existing)Object.assign(existing,item);else state.items.push(item);state.drawerItemId=item.id;state.selectedDate=item.date;saveAndSync();render();openDrawerDetail(item.id);toast("Item saved");});}
function openItemForm(item,dateString=state.selectedDate){
  $("#itemForm").reset();$("#itemId").value=item?.id||"";$("#itemTitle").value=item?.title||"";$("#itemCategory").value=item?.category||"personal";$("#itemType").value=item?.type||"event";$("#itemDate").value=item?.date||dateString||fmtDate(new Date());$("#startTime").value=item?.start||"";$("#endTime").value=item?.end||"";$("#itemLocation").value=item?.location||"";$("#itemImportant").checked=Boolean(item?.important);$("#itemStatus").value=item?.status||"planned";$("#repeatRule").value=item?.repeat||"none";$("#reminderMinutes").value=item?.reminder||"none";$("#allDay").checked=!item?.start;$("#deleteItemButton").hidden=!item;$("#formEyebrow").textContent=item?"EDIT PIN":"NEW PIN";$("#formTitle").textContent=item?"Edit item":"Add an item";renderNoteEditors(item?.notes||[]);toggleTimeFields();$("#itemDialog").showModal();
}
function renderNoteEditors(notes){$("#notesList").innerHTML=notes.map(note=>`<div class="note-row" data-note-id="${note.id}"><textarea rows="2" placeholder="Write a note…">${escapeHTML(note.text)}</textarea><button class="remove-note" type="button" aria-label="Remove note">×</button><span class="note-stamp">${new Date(note.createdAt).toLocaleString()}</span></div>`).join("");$$('.remove-note').forEach(button=>button.addEventListener("click",()=>button.closest(".note-row").remove()));}
function addNoteEditor(){const row=document.createElement("div");row.className="note-row";row.dataset.noteId=crypto.randomUUID();row.innerHTML=`<textarea rows="2" placeholder="Write a note…"></textarea><button class="remove-note" type="button" aria-label="Remove note">×</button><span class="note-stamp">New note</span>`;row.querySelector("button").addEventListener("click",()=>row.remove());$("#notesList").append(row);row.querySelector("textarea").focus();}
function saveItem(){
  if(!$("#itemForm").reportValidity())return;const id=$("#itemId").value||crypto.randomUUID();const notes=$$(".note-row").map(row=>({id:row.dataset.noteId,text:row.querySelector("textarea").value.trim(),createdAt:state.items.find(x=>x.id===id)?.notes.find(n=>n.id===row.dataset.noteId)?.createdAt||new Date().toISOString()})).filter(note=>note.text);const status=$("#itemStatus").value;const item={id,title:$("#itemTitle").value.trim(),category:$("#itemCategory").value,type:$("#itemType").value,date:$("#itemDate").value,start:$("#allDay").checked?"":$("#startTime").value,end:$("#allDay").checked?"":$("#endTime").value,location:$("#itemLocation").value.trim(),notes,important:$("#itemImportant").checked,status,repeat:$("#repeatRule").value,reminder:$("#reminderMinutes").value,completed:status==="completed"};
  const index=state.items.findIndex(x=>x.id===id);if(index>=0)state.items[index]=item;else state.items.push(item);saveAndSync();scheduleLocalNotification(item);$("#itemDialog").close();render();if($("#dayDrawer").classList.contains("open"))renderDrawerItems();toast(index>=0?"Pin updated":"Item pinned");
}
function deleteItem(){const id=$("#itemId").value;if(!id)return;state.items=state.items.filter(item=>item.id!==id);saveAndSync();$("#itemDialog").close();render();if($("#dayDrawer").classList.contains("open"))renderDrawerItems();toast("Item deleted");}
function toggleTimeFields(){const disabled=$("#allDay").checked;$("#startTime").disabled=disabled;$("#endTime").disabled=disabled;}

function search(){
  const query=$("#searchInput").value.trim().toLowerCase(),category=$("#searchCategory").value,type=$("#searchType").value,incomplete=$("#incompleteOnly").checked;let results=state.items.filter(item=>(category==="all"||item.category===category)&&(type==="all"||item.type===type)&&(!incomplete||(item.type==="task"&&!item.completed))&&(!query||[item.title,item.notes.map(n=>n.text).join(" "),item.location,item.date,item.type,item.category,item.important?"important":""].join(" ").toLowerCase().includes(query))).sort((a,b)=>Number(b.important)-Number(a.important)||a.date.localeCompare(b.date)).slice(0,30);
  $("#searchResults").innerHTML=results.map(item=>`<button class="search-result" type="button" data-result="${item.id}"><span><strong>${item.important?"★ ":""}${escapeHTML(item.title)}</strong><br><small>${CATEGORIES[item.category]} · ${TYPES[item.type]}</small></span><small>${longDate(item.date)}</small></button>`).join("")||(query?`<div class="empty-state">No matching pins found.</div>`:"");
  $$('[data-result]').forEach(button=>button.addEventListener("click",()=>{const item=state.items.find(x=>x.id===button.dataset.result);openItemForm(item,item.date);$("#searchPanel").hidden=true;}));
}
function toast(message){const node=$("#toast");node.textContent=message;node.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove("show"),2200);}
async function scheduleLocalNotification(item){
  if(item.reminder==="none"||!item.start||!("Notification" in window))return;if(Notification.permission==="default")await Notification.requestPermission();if(Notification.permission!=="granted")return;
  const when=new Date(`${item.date}T${item.start}:00`).getTime()-Number(item.reminder)*60000,delay=when-Date.now();if(delay>0&&delay<2147483647)setTimeout(()=>new Notification(item.title,{body:item.notes[0]?.text||`${readableTime(item.start)}${item.location?` · ${item.location}`:""}`,icon:"./icons/icon.svg"}),delay);
}

async function initSupabase(){
  const config=window.BULLETIN_BOARD_CONFIG||{};if(!config.supabaseUrl||!config.supabaseAnonKey||!window.supabase)return;
  state.supabase=window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey);const {data}=await state.supabase.auth.getSession();state.user=data.session?.user||null;updateAccountUI();if(state.user)await loadCloud();state.supabase.auth.onAuthStateChange(async(_,session)=>{state.user=session?.user||null;updateAccountUI();if(state.user)await loadCloud();});
}
async function sign(mode){
  if(!state.supabase){$("#syncStatus").textContent="Add your Supabase URL and public key in config.js first.";return;}const email=$("#email").value,password=$("#password").value;if(!email||password.length<8){$("#syncStatus").textContent="Enter an email and a password with at least 8 characters.";return;}
  const action=mode==="up"?state.supabase.auth.signUp({email,password}):state.supabase.auth.signInWithPassword({email,password});const {error}=await action;$("#syncStatus").textContent=error?error.message:(mode==="up"?"Account created. Check your email if confirmation is enabled.":"Signed in and syncing.");
}
function updateAccountUI(){$("#accountButton").textContent=state.user?.email?.slice(0,2).toUpperCase()||"AM";$("#syncStatus").textContent=state.user?`Syncing as ${state.user.email}`:"Local mode is active";}
async function loadCloud(){const {data,error}=await state.supabase.from("calendar_items").select("*").eq("user_id",state.user.id);if(!error&&data?.length){state.items=data.map(row=>row.payload);saveLocal();render();}else if(!error)await syncCloud();}
async function syncCloud(){if(!state.supabase||!state.user)return;await state.supabase.from("calendar_items").delete().eq("user_id",state.user.id);if(state.items.length)await state.supabase.from("calendar_items").insert(state.items.map(item=>({id:item.id,user_id:state.user.id,payload:item})));}
function saveAndSync(){saveLocal();syncCloud();}

function optionTags(values,current){return Object.entries(values).map(([value,label])=>`<option value="${value}" ${value===current?"selected":""}>${label}</option>`).join("");}
function filteredSheetItems(){const q=$("#sheetSearch")?.value.trim().toLowerCase()||"",category=$("#sheetCategory")?.value||"all",status=$("#sheetStatus")?.value||"all",hide=$("#hideFinished")?.checked;return state.items.filter(item=>(category==="all"||item.category===category)&&(status==="all"||item.status===status)&&(!hide||!["completed","cancelled"].includes(item.status))&&(!q||[item.title,item.location,item.notes.map(n=>n.text).join(" "),CATEGORIES[item.category],TYPES[item.type]].join(" ").toLowerCase().includes(q))).sort((a,b)=>Number(b.important)-Number(a.important)||b.date.localeCompare(a.date));}
function expandedRowHTML(item){return `<tr class="expanded-editor" data-expanded="${item.id}"><td colspan="12"><div class="row-advanced"><div class="field"><label>End time</label><input data-advanced="end" type="time" value="${item.end||""}"></div><div class="field"><label>Repeat</label><select data-advanced="repeat">${optionTags({none:"Doesn't repeat",daily:"Daily",weekly:"Weekly",monthly:"Monthly",weekdays:"Weekdays"},item.repeat)}</select></div><div class="field"><label>Notify</label><select data-advanced="reminder">${optionTags({none:"None",0:"At start",10:"10 min before",30:"30 min before",60:"1 hour before",1440:"1 day before"},item.reminder)}</select></div><div class="advanced-actions"><button class="secondary-button" data-duplicate type="button">Duplicate</button></div></div><div class="inline-notes"><div class="notes-heading"><label>Notes</label><button class="text-button" data-add-inline-note type="button">＋ Add note</button></div><div data-inline-notes>${item.notes.map(n=>`<div class="inline-note" data-note-id="${n.id}"><textarea rows="2">${escapeHTML(n.text)}</textarea><button type="button" data-remove-inline-note>×</button></div>`).join("")}</div></div></td></tr>`;}
function renderItemsTable(){
  if(!$("#itemsTableBody"))return;const items=filteredSheetItems();$("#itemsTableBody").innerHTML=items.map(item=>`<tr data-row="${item.id}" class="${item.status}"><td><input class="row-select" type="checkbox" ${state.selectedRows.has(item.id)?"checked":""}></td><td><button class="row-expand" type="button" aria-label="Expand row">${state.expandedRows.has(item.id)?"⌄":"›"}</button></td><td><button class="sheet-star ${item.important?"on":""}" data-field="important" type="button">★</button></td><td><input data-field="title" value="${escapeHTML(item.title)}" placeholder="New item"></td><td><select data-field="category">${optionTags(CATEGORIES,item.category)}</select></td><td><select data-field="type">${optionTags(TYPES,item.type)}</select></td><td><input data-field="date" type="date" value="${item.date}"></td><td><input data-field="start" type="time" value="${item.start||""}"></td><td><input data-field="location" value="${escapeHTML(item.location)}" placeholder="Location or URL"></td><td><select data-field="status">${optionTags({planned:"Planned",progress:"In progress",completed:"Completed",cancelled:"Cancelled"},item.status)}</select></td><td><button class="notes-count" data-expand-notes type="button">${item.notes.length} note${item.notes.length===1?"":"s"}</button></td><td><button class="row-delete" type="button" aria-label="Delete row">×</button></td></tr>${state.expandedRows.has(item.id)?expandedRowHTML(item):""}`).join("");
  $("#sheetCount").textContent=`${items.length} item${items.length===1?"":"s"} shown · ${state.selectedRows.size} selected`;$("#deleteSelectedButton").disabled=!state.selectedRows.size;
  $$("#itemsTableBody tr[data-row]").forEach(row=>{const item=state.items.find(x=>x.id===row.dataset.row);row.querySelector(".row-select").addEventListener("change",event=>{event.target.checked?state.selectedRows.add(item.id):state.selectedRows.delete(item.id);renderItemsTable();});row.querySelector(".row-expand").addEventListener("click",()=>{state.expandedRows.has(item.id)?state.expandedRows.delete(item.id):state.expandedRows.add(item.id);renderItemsTable();});row.querySelector('[data-expand-notes]').addEventListener("click",()=>{state.expandedRows.add(item.id);renderItemsTable();});row.querySelector('.row-delete').addEventListener("click",()=>deleteItems([item.id]));row.querySelectorAll("[data-field]").forEach(control=>{const save=()=>{const field=control.dataset.field;if(field==="important")item.important=!item.important;else item[field]=control.value;if(field==="status")item.completed=control.value==="completed";saveAndSync();render();};control.addEventListener(control.tagName==="BUTTON"?"click":"change",save);});});
  $$("#itemsTableBody tr[data-expanded]").forEach(row=>{const item=state.items.find(x=>x.id===row.dataset.expanded);row.querySelectorAll('[data-advanced]').forEach(control=>control.addEventListener("change",()=>{item[control.dataset.advanced]=control.value;saveAndSync();render();}));row.querySelector('[data-duplicate]').addEventListener("click",()=>duplicateItem(item));row.querySelector('[data-add-inline-note]').addEventListener("click",()=>{item.notes.push({id:crypto.randomUUID(),text:"",createdAt:new Date().toISOString()});saveAndSync();renderItemsTable();});row.querySelectorAll('.inline-note').forEach(noteRow=>{noteRow.querySelector('textarea').addEventListener("change",event=>{const note=item.notes.find(n=>n.id===noteRow.dataset.noteId);note.text=event.target.value;saveAndSync();render();});noteRow.querySelector('[data-remove-inline-note]').addEventListener("click",()=>{item.notes=item.notes.filter(n=>n.id!==noteRow.dataset.noteId);saveAndSync();render();});});});
}
function addSheetRow(){const item=normalizeItem({id:crypto.randomUUID(),title:"",category:"personal",type:"task",date:fmtDate(new Date()),start:"",end:"",location:"",status:"planned",important:false,notes:[],repeat:"none",reminder:"none"});state.items.push(item);state.expandedRows.add(item.id);saveAndSync();renderItemsTable();setTimeout(()=>document.querySelector(`[data-row="${item.id}"] [data-field="title"]`)?.focus(),0);}
function duplicateItem(source){const item=normalizeItem({...source,id:crypto.randomUUID(),title:`${source.title} copy`,notes:source.notes.map(n=>({...n,id:crypto.randomUUID()}))});state.items.push(item);state.expandedRows.add(item.id);saveAndSync();render();toast("Item duplicated");}
function deleteItems(ids){state.undoItems=state.items.filter(item=>ids.includes(item.id));state.items=state.items.filter(item=>!ids.includes(item.id));ids.forEach(id=>{state.selectedRows.delete(id);state.expandedRows.delete(id)});saveAndSync();render();toastUndo(`${ids.length} item${ids.length===1?"":"s"} deleted`);}
function deleteSelected(){if(state.selectedRows.size)deleteItems([...state.selectedRows]);}
function toastUndo(message){const node=$("#toast");node.innerHTML=`${message} <button type="button">Undo</button>`;node.classList.add("show");node.querySelector("button").addEventListener("click",()=>{state.items.push(...state.undoItems);state.undoItems=[];saveAndSync();render();node.classList.remove("show");});clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove("show"),5000);}
function importRows(){
  const rows=$("#importText").value.trim().split(/\r?\n/).filter(Boolean);if(!rows.length)return;const categoryLookup=Object.fromEntries(Object.entries(CATEGORIES).map(([k,v])=>[v.toLowerCase(),k])),typeLookup=Object.fromEntries(Object.entries(TYPES).map(([k,v])=>[v.toLowerCase(),k]));for(const row of rows){const [title,category,type,date,time,status,important,note]=row.split("\t");if(!title?.trim())continue;state.items.push(normalizeItem({id:crypto.randomUUID(),title:title.trim(),category:categoryLookup[(category||"").trim().toLowerCase()]||"personal",type:typeLookup[(type||"").trim().toLowerCase()]||"task",date:/^\d{4}-\d{2}-\d{2}$/.test(date||"")?date:fmtDate(new Date()),start:time||"",end:"",location:"",status:["planned","progress","completed","cancelled"].includes((status||"").trim().toLowerCase())?status.trim().toLowerCase():"planned",important:/^(yes|true|star|important)$/i.test(important||""),notes:note?[{id:crypto.randomUUID(),text:note.trim(),createdAt:new Date().toISOString()}]:[],repeat:"none",reminder:"none"}));}saveAndSync();$("#importDialog").close();$("#importText").value="";render();toast(`${rows.length} rows imported`);
}

function bind(){
  function showPage(page){state.page=page;$("#dashboardPage").hidden=page!=="dashboard";$("#calendarPage").hidden=page!=="calendar";$("#itemsPage").hidden=page!=="items";$$('[data-page]').forEach(button=>button.classList.toggle("active",button.dataset.page===page));if(page==="calendar")render();else if(page==="items")renderItemsTable();else renderDashboard();}
  $$('[data-page]').forEach(button=>button.addEventListener("click",()=>showPage(button.dataset.page)));$$('[data-go-calendar]').forEach(button=>button.addEventListener("click",()=>showPage("calendar")));$(".dashboard-add").addEventListener("click",()=>openItemForm(null,fmtDate(new Date())));
  $$(".view-switcher button").forEach(button=>button.addEventListener("click",()=>{state.view=button.dataset.view;render();}));
  $("#previousButton").addEventListener("click",()=>{state.cursor=state.view==="week"?addDays(state.cursor,-7):new Date(state.cursor.getFullYear(),state.cursor.getMonth()-1,1);render();});
  $("#nextButton").addEventListener("click",()=>{state.cursor=state.view==="week"?addDays(state.cursor,7):new Date(state.cursor.getFullYear(),state.cursor.getMonth()+1,1);render();});
  $("#todayButton").addEventListener("click",()=>{state.cursor=new Date();render();});$("#addItemButton").addEventListener("click",()=>openItemForm(null,fmtDate(new Date())));$("#drawerAddButton").addEventListener("click",()=>openDrawerForm());$("#drawerEditButton").addEventListener("click",()=>openDrawerForm(state.items.find(x=>x.id===state.drawerItemId)));$$('[data-drawer-back]').forEach(button=>button.addEventListener("click",()=>showDrawerView("day")));
  $("#scrim").addEventListener("click",closeDay);$("[data-close-drawer]").addEventListener("click",closeDay);$("#saveItemButton").addEventListener("click",saveItem);$("#deleteItemButton").addEventListener("click",deleteItem);$("#allDay").addEventListener("change",toggleTimeFields);$("#addNoteButton").addEventListener("click",addNoteEditor);
  $$("dialog").forEach(dialog=>{dialog.querySelectorAll(".close-dialog").forEach(button=>button.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();dialog.close();}));dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close();});dialog.addEventListener("cancel",event=>{event.preventDefault();dialog.close();});});
  $("#dailyReminder").addEventListener("input",()=>{state.reminders[state.selectedDate]=$("#dailyReminder").value;saveAndSync();});
  $(".search-toggle").addEventListener("click",()=>{$("#searchPanel").hidden=!$("#searchPanel").hidden;if(!$("#searchPanel").hidden){$("#searchInput").focus();search();}});["#searchInput","#searchCategory","#searchType","#incompleteOnly"].forEach(selector=>$(selector).addEventListener("input",search));
  $("#accountButton").addEventListener("click",()=>$("#accountDialog").showModal());$("#signInButton").addEventListener("click",()=>sign("in"));$("#signUpButton").addEventListener("click",()=>sign("up"));
  ["#sheetSearch","#sheetCategory","#sheetStatus","#hideFinished"].forEach(selector=>$(selector).addEventListener("input",renderItemsTable));$("#selectAllRows").addEventListener("change",event=>{filteredSheetItems().forEach(item=>event.target.checked?state.selectedRows.add(item.id):state.selectedRows.delete(item.id));renderItemsTable();});$("#deleteSelectedButton").addEventListener("click",deleteSelected);$("#addRowButton").addEventListener("click",addSheetRow);$("#importRowsButton").addEventListener("click",()=>$("#importDialog").showModal());$("#processImportButton").addEventListener("click",importRows);
  document.addEventListener("click",event=>{if(!event.target.closest("#searchPanel")&&!event.target.closest(".search-toggle"))$("#searchPanel").hidden=true;});document.addEventListener("keydown",event=>{if(event.key==="Escape"){closeDay();$("#searchPanel").hidden=true;}if(event.key==="/"&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){event.preventDefault();$("#searchPanel").hidden=false;$("#searchInput").focus();search();}});showPage("dashboard");
}

bind();render();initSupabase();if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js?v=5"));
